import { Product, Category } from "@/types/product";

export const categories: Category[] = [
  { id: "all", name: "Todos" },
  { id: "sorvetes", name: "Sorvetes" },
  { id: "milkshakes", name: "Milkshakes" },
  { id: "casquinhas", name: "Casquinhas" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Milkshake de Morango",
    description: "Milkshake cremoso de morango com chantilly e morangos frescos",
    price: 18.90,
    image: "/images/products/product-1.jpg",
    category: "milkshakes",
    available: true,
    featured: true,
  },
  {
    id: "2",
    name: "Pote 500ml Morango e Baunilha",
    description: "Pote de sorvete com morango e baunilha cremosos",
    price: 32.90,
    image: "/images/products/product-2.jpg",
    category: "sorvetes",
    available: true,
  },
  {
    id: "3",
    name: "Casquinha 3 Sabores",
    description: "Casquinha crocante com 3 bolas de sorvete",
    price: 15.90,
    image: "/images/products/product-3.jpg",
    category: "casquinhas",
    available: true,
  },
  {
    id: "4",
    name: "Milkshake de Caramelo",
    description: "Milkshake cremoso de caramelo com chantilly",
    price: 18.90,
    image: "/images/products/product-4.jpg",
    category: "milkshakes",
    available: true,
  },
  {
    id: "5",
    name: "Pote 500ml Chocolate",
    description: "Pote de sorvete de chocolate belga cremoso",
    price: 32.90,
    image: "/images/products/product-2.jpg",
    category: "sorvetes",
    available: true,
  },
  {
    id: "6",
    name: "Milkshake de Chocolate",
    description: "Milkshake cremoso de chocolate com chantilly",
    price: 18.90,
    image: "/images/products/product-4.jpg",
    category: "milkshakes",
    available: true,
  },
  {
    id: "7",
    name: "Açaí 500ml",
    description: "Açaí cremoso com granola, banana, morango e mel",
    price: 19.90,
    image: "/images/products/product-1.jpg",
    category: "sorvetes",
    available: true,
    featured: true,
  },
  {
    id: "8",
    name: "Casquinha Dupla",
    description: "Casquinha crocante com 2 bolas de sorvete",
    price: 12.90,
    image: "/images/products/product-3.jpg",
    category: "casquinhas",
    available: true,
  },
  {
    id: "10",
    name: "Pote 300ml Baunilha",
    description: "Pote de sorvete de baunilha cremoso",
    price: 24.90,
    image: "/images/products/product-2.jpg",
    category: "sorvetes",
    available: true,
  },
];

